CONFIG_PREFIX=/home/ibrahim/.config

VIMRC_PREFIX=/home/ibrahim
VIMRC_FILE=.vimrc

XINITRC_PREFIX=/home/ibrahim
XINITRC_FILE=.xinitrc

FISHRC_PREFIX=$(CONFIG_PREFIX)/fish
FISHRC_FILE=.fishrc

CAVA_PREFIX=$(CONFIG_PREFIX)/cava
CAVA_FILE=cava_config
CAVA_FILE_INSTALL_NAME=config

I3_PREFIX=$(CONFIG_PREFIX)/i3
I3_FILE=i3_config
I3_FILE_INSTALL_NAME=config

install:
	cp $(VIMRC_FILE) $(VIMRC_PREFIX)/$(VIMRC_FILE)
	cp $(XINITRC_FILE) $(XINITRC_PREFIX)/$(XINITRC_FILE)
	cp $(FISHRC_FILE) $(FISHRC_PREFIX)/$(FISHRC_FILE)
	cp $(CAVA_FILE) $(CAVA_PREFIX)/$(CAVA_FILE_INSTALL_NAME)
	cp $(I3_FILE) $(I3_PREFIX)/$(I3_FILE_INSTALL_NAME)
