CONFIG_PREFIX=/home/ibrahim/.config

VIMRC_PREFIX=/home/ibrahim
VIMRC_FILE=.vimrc

XINITRC_PREFIX=/home/ibrahim
XINITRC_FILE=.xinitrc

FISHRC_PREFIX=$(CONFIG_PREFIX)/fish
FISHRC_FILE=.fishrc

CAVA_PREFIX=$(CONFIG_PREFIX)/cava
CAVA_FILE=cava_config
CAVA_FILE_INSTALL_NAME=config

I3_PREFIX=$(CONFIG_PREFIX)/i3
I3_FILE=i3_config
I3_FILE_INSTALL_NAME=config

DUNST_PREFIX=$(CONFIG_PREFIX)/dunst
DUNST_FILE=dunstrc

MPD_PREFIX=$(CONFIG_PREFIX)/mpd
MPD_FILE=mpd.conf

NEOFETCH_PREFIX=$(CONFIG_PREFIX)/neofetch
NEOFETCH_FILE=neofetch_config
NEOFETCH_FILE_INSTALL_NAME=config.conf

ROFI_PREFIX=$(CONFIG_PREFIX)/rofi
ROFI_FILE=rofi_config
ROFI_FILE_INSTALL_NAME=config.rasi

SPICETIFY_PREFIX=$(CONFIG_PREFIX)/spicetify
SPICETIFY_FILE=spicetify_config
SPICETIFY_FILE_INSTALL_NAME=config.ini

install:
	cp $(VIMRC_FILE) $(VIMRC_PREFIX)/$(VIMRC_FILE)
	cp $(XINITRC_FILE) $(XINITRC_PREFIX)/$(XINITRC_FILE)
	cp $(FISHRC_FILE) $(FISHRC_PREFIX)/$(FISHRC_FILE)
	cp $(CAVA_FILE) $(CAVA_PREFIX)/$(CAVA_FILE_INSTALL_NAME)
	cp $(I3_FILE) $(I3_PREFIX)/$(I3_FILE_INSTALL_NAME)
	cp $(DUNST_FILE) $(DUNST_PREFIX)/$(DUNST_FILE)
	cp $(MPD_FILE) $(DUNST_PREFIX)/$(MPD_FILE)
	cp $(NEOFETCH_FILE) $(NEOFETCH_PREFIX)/$(NEOFETCH_FILE_INSTALL_NAME)
	cp $(ROFI_FILE) $(ROFI_PREFIX)/$(ROFI_FILE_INSTALL_NAME)
	cp $(SPICETIFY_FILE) $(SPICETIFY_PREFIX)/$(SPICETIFY_FILE_INSTALL_NAME)